import minecraftSkinPreview from './library/prompts/minecraft-skin-preview.md?raw'

export const libraryEntries = [
  {
    id: 'minecraft-skin-preview',
    type: 'prompt',
    no: '001',
    titleKey: 'library.entries.minecraftSkinPreview.title',
    descriptionKey: 'library.entries.minecraftSkinPreview.description',
    detailKey: 'minecraftSkinPreview',
    content: minecraftSkinPreview,
    tags: ['minecraft', 'imageGeneration'],
    version: 'v1.0.0',
    updated: '2026.08.03',
  },
  {
    id: 'threejs-fundamentals',
    type: 'skill',
    sourceType: 'external',
    no: '002',
    titleKey: 'library.entries.threejsFundamentals.title',
    descriptionKey: 'library.entries.threejsFundamentals.description',
    detailKey: 'threejsFundamentals',
    tags: ['threejs', 'webgl', 'vue'],
    version: 'v1.0.0',
    updated: '2026.08.10',
    sourceUrl: 'https://github.com/CloudAI-X/threejs-skills',
    sourceRef: { commit: 'b1c623076c661fc9b03dac19292e825a5d106823' },
    license: 'MIT',
    outline: [
      { level: 1, title: 'threejs-animation' },
      { level: 1, title: 'threejs-fundamentals' },
      { level: 1, title: 'threejs-geometry' },
      { level: 1, title: 'threejs-interaction' },
      { level: 1, title: 'threejs-lighting' },
      { level: 1, title: 'threejs-loaders' },
      { level: 1, title: 'threejs-materials' },
      { level: 1, title: 'threejs-postprocessing' },
      { level: 1, title: 'threejs-shaders' },
      { level: 1, title: 'threejs-textures' },
    ],
  },
  {
    id: 'gsap-core',
    type: 'skill',
    sourceType: 'external',
    no: '003',
    titleKey: 'library.entries.gsapCore.title',
    descriptionKey: 'library.entries.gsapCore.description',
    detailKey: 'gsapCore',
    tags: ['gsap', 'animation', 'vue'],
    version: 'v1.0.0',
    updated: '2026.08.10',
    sourceUrl: 'https://github.com/greensock/gsap-skills',
    sourceRef: { commit: 'aed9cfd3277740755f6bfc1155c7aa645403b760' },
    license: 'MIT',
    installCommand: 'npx skills add https://github.com/greensock/gsap-skills',
    outline: [
      { level: 1, title: 'gsap-core' },
      { level: 1, title: 'gsap-frameworks' },
      { level: 1, title: 'gsap-performance' },
      { level: 1, title: 'gsap-plugins' },
      { level: 1, title: 'gsap-react' },
      { level: 1, title: 'gsap-scrolltrigger' },
      { level: 1, title: 'gsap-timeline' },
      { level: 1, title: 'gsap-utils' },
    ],
  },
]

export function getLibraryEntry(id) {
  return libraryEntries.find((entry) => entry.id === id) || null
}
