/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    colors: {
      inherit: "inherit",
      current: "currentColor",
      transparent: "transparent",
      white: "var(--card)",
      black: "var(--ink)",
      background: "var(--background)",
      foreground: "var(--foreground)",
      ink: "var(--ink)",
      card: "var(--card)",
      "card-foreground": "var(--card-foreground)",
      popover: "var(--popover)",
      "popover-foreground": "var(--popover-foreground)",
      primary: "var(--primary)",
      "primary-foreground": "var(--primary-foreground)",
      secondary: "var(--secondary)",
      "secondary-foreground": "var(--secondary-foreground)",
      muted: "var(--muted)",
      "muted-foreground": "var(--muted-foreground)",
      accent: "var(--accent)",
      "accent-foreground": "var(--accent-foreground)",
      destructive: "var(--destructive)",
      haze: "var(--haze)",
      border: "var(--border)",
      input: "var(--input)",
      ring: "var(--ring)",
      line: "var(--line)",
      "line-strong": "var(--line-strong)",
      blue: "var(--blue)",
      "blue-soft": "var(--blue-soft)",
      gray: {
        50: "var(--card)",
        100: "var(--muted)",
        200: "var(--border)",
        300: "var(--line-strong)",
        400: "var(--haze)",
        500: "var(--muted-foreground)",
        600: "var(--muted-foreground)",
        700: "#30343b",
        800: "#25292f",
        900: "var(--ink)",
      },
      red: {
        50: "#fff0ee",
        200: "#fed2cd",
        700: "#90302e",
      },
      green: {
        50: "#e9faf2",
        200: "#c0e9d6",
        500: "#009267",
        600: "#007852",
        700: "#006042",
      },
    },
    borderRadius: {
      none: "0",
      sm: "0.125rem",
      DEFAULT: "var(--radius)",
      md: "var(--radius)",
      lg: "var(--radius)",
      xl: "var(--radius)",
      "2xl": "var(--radius)",
      "3xl": "var(--radius)",
      full: "9999px",
    },
    boxShadow: {
      sm: "none",
      DEFAULT: "none",
      md: "none",
      lg: "none",
      xl: "none",
      "2xl": "none",
      inner: "none",
      none: "none",
    },
    fontFamily: {
      sans: ["Geist", "Inter", "ui-sans-serif", "system-ui", "sans-serif"],
      mono: ["Geist Mono", "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
    },
    extend: {
      transitionTimingFunction: {
        premium: "var(--ease-premium)",
      },
      transitionDuration: {
        reveal: "900ms",
      },
    },
  },
  plugins: [],
}
