// Footer翻译文本常量
export const footerTexts = {
  "zh-cn": {
    companyName: "Jacory Space",
    slogan: "认知是序章，行走才是长诗",
    email: "邮箱: chengyue.jin@outlook.com",
    navigation: "导航",
    projects: "项目",
    legal: "法律",
    home: "首页",
    portfolio: "作品集",
    blog: "博客",
    about: "关于我",
    contact: "联系我",
    featuredProjects: "精选项目",
    webDevelopment: "网页开发",
    mobileApps: "移动应用",
    uiuxDesign: "UI/UX设计",
    imprint: "版权声明",
    privacyPolicy: "隐私政策",
    termsOfService: "服务条款",
    copyright: "版权所有",
    allRightsReserved: "保留所有权利"
  },
  "zh-tw": {
    companyName: "Jacory Space",
    slogan: "認知是序章，行走才是長詩",
    email: "郵箱: chengyue.jin@outlook.com",
    navigation: "導航",
    projects: "項目",
    legal: "法律",
    home: "首頁",
    portfolio: "作品集",
    blog: "博客",
    about: "關於我",
    contact: "聯繫我",
    featuredProjects: "精選項目",
    webDevelopment: "網頁開發",
    mobileApps: "移動應用",
    uiuxDesign: "UI/UX設計",
    imprint: "版權聲明",
    privacyPolicy: "隱私政策",
    termsOfService: "服務條款",
    copyright: "版權所有",
    allRightsReserved: "保留所有權利"
  },
  en: {
    companyName: "Jacory Space",
    slogan: "Knowledge is the prelude, walking is the epic",
    email: "E-Mail: chengyue.jin@outlook.com",
    navigation: "Navigation",
    projects: "Projects",
    legal: "Legal",
    home: "Home",
    portfolio: "Portfolio",
    blog: "Blog",
    about: "About",
    contact: "Contact",
    featuredProjects: "Featured Projects",
    webDevelopment: "Web Development",
    mobileApps: "Mobile Apps",
    uiuxDesign: "UI/UX Design",
    imprint: "Imprint",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    copyright: "Copyright",
    allRightsReserved: "All rights reserved"
  }
};
