import type { Metadata } from 'next';
import './globals.scss';
import NavBar from '@/components/NavBar/NavBar';
import Footer from '@/components/Footer/Footer';
import ScrollToTop from '@/components/ScrollToTop/ScrollToTop';

export const metadata: Metadata = {
  title: '芥子不才',
  description: 'Generated by create next app',
  icons: {
    icon: '/images/logo.png',
    // 您也可以添加其他尺寸
    apple: '/apple-icon.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode,
}>) {
  return (
    <html lang="en">
      <body className="antialiased flex-row">
        <NavBar />
        <main className="">{children}</main>
        <ScrollToTop />
        <Footer />
      </body>
    </html>
  );
}
