import type { Metadata } from 'next';
import './globals.css';
import NavBar from '@/components/NavBar/NavBar';

export const metadata: Metadata = {
  title: '芥子不才',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode,
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <NavBar />
        <main className="">{children}</main>
      </body>
    </html>
  );
}
