import "./globals.css";
import NavBar from "@/components/NavBar";
import { AppProvider } from "@/lib/context";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          <NavBar />
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
